### PR TITLE
FIXED - different const values

### PR DESCRIPTION
**Pull request by ptopczewski**
@nikic 
the node kinds and the const values in the stub were different

### CODE REVIEW

**Comment by nikic** [comment]
The specific values depend on the PHP version, iirc I generated the stubs from 7.1. The actual values are irrelevant in any case, as the stubs are for code completion only. Maybe it would be better to replace the specific values with some kind of dummy (like set all of them to 0) to avoid confusion?

**Comment by ptopczewski** [comment]
oh ok,
i have used the const values to determine the kind of nodes :D
... nevermind

**Comment by nikic** [comment]
@ptopczewski But why? Why can't you use the constants instead?

**Comment by ptopczewski** [comment]
@nikic 
 i'm using the constants atm. I've just used the stub for getting an overview of the nodes.

**Comment by nikic** [comment]
@ptopczewski In case you haven't seen it, there's a node overview in the readme here: https://github.com/nikic/php-ast#ast-node-kinds It's probably a bit more informative than the stub as it also lists the subnode names :)

**Pull request closed without merging**
