### PR TITLE
Update current version in docs to 70

### PR DESCRIPTION
**Pull request by TysonAndre**
Also, fix grammar nits.

(there should be commas after "Furthermore". More common choices such as
"Next,"/"Then," might be more conventional for installation instructions)

### CODE REVIEW

**Comment by nikic** [comment]
Not a fan of those grammar changes. The third comma is fine, but the first two are stylistically inappropriate, even if grammatically permissible.

**Comment by TysonAndre** [comment]
https://sentence.yourdictionary.com/furthermore

The main reason for this was that at the start of a sentence, furthermore is usually followed by a comma

**Comment by TysonAndre** [comment]
https://grammar.yourdictionary.com/parts-of-speech/adverbs/con-adverb.html was the general rule suggested by the spell checker

> Many times, a conjunctive adverb will start or end a sentence. At the beginning of a sentence it may need a comma after it since it appears before an independent clause. Here are some examples:

**Comment by nikic** [comment]
@TysonAndre The relevant difference here is that furthermore/additionally are directly followed by a verb in the first two cases and (may) function as plain adverbs rather than a conjunctive adverb followed by an independent clause.

**Comment by TysonAndre** [comment]
Ok, makes sense

**Pull request merged**
