### PR TITLE
Fix version in Reflection

### PR DESCRIPTION
**Pull request by TysonAndre**

### CODE REVIEW

**Comment by nikic** [comment]
Doesn't look like 1.0.5 is already released, so why the additional bump?

**Comment by TysonAndre** [comment]
I published a 1.0.5 tag on GitHub and didn't know if anyone would care about invalidating that tag after releasing it

**Comment by nikic** [comment]
Retagging is fine so long as the PECL release isn't uploaded.

**Comment by TysonAndre** [comment]
ok

**Pull request merged**
